/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeAPartnerRouteImport } from './routes/become-a-partner'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as DoBusinessRouteImport } from './routes/do-business'
import { Route as EgyptAppsRouteImport } from './routes/egypt-apps'
import { Route as EgyptThroughTimeRouteImport } from './routes/egypt-through-time'
import { Route as EgyptianHeritageWorldwideRouteImport } from './routes/egyptian-heritage-worldwide'
import { Route as EmergencyNumbersRouteImport } from './routes/emergency-numbers'
import { Route as EncyclopediaRouteImport } from './routes/encyclopedia'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ExploreEgyptRouteImport } from './routes/explore-egypt'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as GovernmentDirectoryRouteImport } from './routes/government-directory'
import { Route as HeritageSitesRouteImport } from './routes/heritage-sites'
import { Route as InvestInEgyptRouteImport } from './routes/invest-in-egypt'
import { Route as InvestmentOpportunitiesRouteImport } from './routes/investment-opportunities'
import { Route as KnowYourRootsRouteImport } from './routes/know-your-roots'
import { Route as LiveInEgyptRouteImport } from './routes/live-in-egypt'
import { Route as LiveLikeAnEgyptianRouteImport } from './routes/live-like-an-egyptian'
import { Route as MuseumsRouteImport } from './routes/museums'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OurMissionRouteImport } from './routes/our-mission'
import { Route as PhotoCreditsRouteImport } from './routes/photo-credits'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as ResearchProgramsRouteImport } from './routes/research-programs'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TravelerStoriesRouteImport } from './routes/traveler-stories'
import { Route as TrustCenterRouteImport } from './routes/trust-center'
import { Route as VisionValuesRouteImport } from './routes/vision-values'
import { Route as VisitEgyptRouteImport } from './routes/visit-egypt'
import { Route as AccountBookingsRouteImport } from './routes/account_.bookings'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiConciergeRouteImport } from './routes/api/concierge'
import { Route as CountriesIdRouteImport } from './routes/countries_.$id'
import { Route as DoBusinessGuideRouteImport } from './routes/do-business_.$guide'
import { Route as EgyptAppsCategoryRouteImport } from './routes/egypt-apps_.$category'
import { Route as EgyptThroughTimeMilitaryHistoryRouteImport } from './routes/egypt-through-time_.military-history'
import { Route as EgyptianHeritageWorldwideIdRouteImport } from './routes/egyptian-heritage-worldwide_.$id'
import { Route as EventsIdRouteImport } from './routes/events_.$id'
import { Route as ExperiencesTypeRouteImport } from './routes/experiences.$type'
import { Route as GovernmentDirectoryDigitalServicesRouteImport } from './routes/government-directory_.digital-services'
import { Route as GovernoratesIndexRouteImport } from './routes/governorates.index'
import { Route as GovernoratesIdRouteImport } from './routes/governorates.$id'
import { Route as HeritageSitesIdRouteImport } from './routes/heritage-sites_.$id'
import { Route as InvestmentOpportunitiesIdRouteImport } from './routes/investment-opportunities_.$id'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as LegalConsentRouteImport } from './routes/legal.consent'
import { Route as LegalReviewChecklistRouteImport } from './routes/legal.review-checklist'
import { Route as LiveInEgyptGuideRouteImport } from './routes/live-in-egypt_.$guide'
import { Route as LiveLikeAnEgyptianSectionRouteImport } from './routes/live-like-an-egyptian_.$section'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceEgyptianCottonRouteImport } from './routes/marketplace.egyptian-cotton'
import { Route as MarketplaceHandmadeCraftsRouteImport } from './routes/marketplace.handmade-crafts'
import { Route as MarketplaceLocalProducersRouteImport } from './routes/marketplace.local-producers'
import { Route as MarketplaceWearEgyptRouteImport } from './routes/marketplace.wear-egypt'
import { Route as MuseumsIdRouteImport } from './routes/museums_.$id'
import { Route as MyTripsIndexRouteImport } from './routes/my-trips.index'
import { Route as MyTripsNewRouteImport } from './routes/my-trips.new'
import { Route as OffersIdRouteImport } from './routes/offers_.$id'
import { Route as PartnersIndexRouteImport } from './routes/partners.index'
import { Route as PlacesIdRouteImport } from './routes/places.$id'
import { Route as ProductsIdRouteImport } from './routes/products_.$id'
import { Route as PropertiesIdRouteImport } from './routes/properties_.$id'
import { Route as ProvidersIdRouteImport } from './routes/providers_.$id'
import { Route as ResearchProgramsIdRouteImport } from './routes/research-programs_.$id'
import { Route as TravelerStoriesIdRouteImport } from './routes/traveler-stories_.$id'
import { Route as TripsIdRouteImport } from './routes/trips.$id'
import { Route as VisitEgyptEVisaRouteImport } from './routes/visit-egypt_.e-visa'
import { Route as VisitEgyptTravelAndTourismRouteImport } from './routes/visit-egypt_.travel-and-tourism'
import { Route as AdminContentIndexRouteImport } from './routes/admin.content.index'
import { Route as AdminContentTableRouteImport } from './routes/admin.content.$table'
import { Route as AdminCrmInvestmentRouteImport } from './routes/admin.crm.investment'
import { Route as AdminCrmPropertiesRouteImport } from './routes/admin.crm.properties'
import { Route as AdminPartnersNewRouteImport } from './routes/admin.partners_.new'
import { Route as EgyptThroughTimeMilitaryHistoryFiguresRouteImport } from './routes/egypt-through-time_.military-history_.figures'
import { Route as EgyptThroughTimeMilitaryHistoryLibraryRouteImport } from './routes/egypt-through-time_.military-history_.library'
import { Route as EgyptThroughTimeMilitaryHistoryMapRouteImport } from './routes/egypt-through-time_.military-history_.map'
import { Route as EgyptThroughTimeMilitaryHistoryRecordsRouteImport } from './routes/egypt-through-time_.military-history_.records'
import { Route as EgyptThroughTimeMilitaryHistoryTimelineRouteImport } from './routes/egypt-through-time_.military-history_.timeline'
import { Route as LiveLikeAnEgyptianSectionSlugRouteImport } from './routes/live-like-an-egyptian_.$section_.$slug'
import { Route as PartnersTypeIdRouteImport } from './routes/partners.$type.$id'
import { Route as ApiPublicHooksProviderRouteImport } from './routes/api/public/hooks/$provider'
import { Route as EgyptThroughTimeMilitaryHistoryFiguresSlugRouteImport } from './routes/egypt-through-time_.military-history_.figures_.$slug'
import { Route as EgyptThroughTimeMilitaryHistoryRecordsSlugRouteImport } from './routes/egypt-through-time_.military-history_.records_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAPartnerRoute = BecomeAPartnerRouteImport.update({
  id: '/become-a-partner',
  path: '/become-a-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const DoBusinessRoute = DoBusinessRouteImport.update({
  id: '/do-business',
  path: '/do-business',
  getParentRoute: () => rootRouteImport,
} as any)
const EgyptAppsRoute = EgyptAppsRouteImport.update({
  id: '/egypt-apps',
  path: '/egypt-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const EgyptThroughTimeRoute = EgyptThroughTimeRouteImport.update({
  id: '/egypt-through-time',
  path: '/egypt-through-time',
  getParentRoute: () => rootRouteImport,
} as any)
const EgyptianHeritageWorldwideRoute =
  EgyptianHeritageWorldwideRouteImport.update({
    id: '/egyptian-heritage-worldwide',
    path: '/egyptian-heritage-worldwide',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmergencyNumbersRoute = EmergencyNumbersRouteImport.update({
  id: '/emergency-numbers',
  path: '/emergency-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const EncyclopediaRoute = EncyclopediaRouteImport.update({
  id: '/encyclopedia',
  path: '/encyclopedia',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreEgyptRoute = ExploreEgyptRouteImport.update({
  id: '/explore-egypt',
  path: '/explore-egypt',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentDirectoryRoute = GovernmentDirectoryRouteImport.update({
  id: '/government-directory',
  path: '/government-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageSitesRoute = HeritageSitesRouteImport.update({
  id: '/heritage-sites',
  path: '/heritage-sites',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestInEgyptRoute = InvestInEgyptRouteImport.update({
  id: '/invest-in-egypt',
  path: '/invest-in-egypt',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentOpportunitiesRoute = InvestmentOpportunitiesRouteImport.update({
  id: '/investment-opportunities',
  path: '/investment-opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowYourRootsRoute = KnowYourRootsRouteImport.update({
  id: '/know-your-roots',
  path: '/know-your-roots',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveInEgyptRoute = LiveInEgyptRouteImport.update({
  id: '/live-in-egypt',
  path: '/live-in-egypt',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveLikeAnEgyptianRoute = LiveLikeAnEgyptianRouteImport.update({
  id: '/live-like-an-egyptian',
  path: '/live-like-an-egyptian',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseumsRoute = MuseumsRouteImport.update({
  id: '/museums',
  path: '/museums',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OurMissionRoute = OurMissionRouteImport.update({
  id: '/our-mission',
  path: '/our-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoCreditsRoute = PhotoCreditsRouteImport.update({
  id: '/photo-credits',
  path: '/photo-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchProgramsRoute = ResearchProgramsRouteImport.update({
  id: '/research-programs',
  path: '/research-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelerStoriesRoute = TravelerStoriesRouteImport.update({
  id: '/traveler-stories',
  path: '/traveler-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustCenterRoute = TrustCenterRouteImport.update({
  id: '/trust-center',
  path: '/trust-center',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionValuesRoute = VisionValuesRouteImport.update({
  id: '/vision-values',
  path: '/vision-values',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitEgyptRoute = VisitEgyptRouteImport.update({
  id: '/visit-egypt',
  path: '/visit-egypt',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookingsRoute = AccountBookingsRouteImport.update({
  id: '/account_/bookings',
  path: '/account/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiConciergeRoute = ApiConciergeRouteImport.update({
  id: '/api/concierge',
  path: '/api/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIdRoute = CountriesIdRouteImport.update({
  id: '/countries_/$id',
  path: '/countries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoBusinessGuideRoute = DoBusinessGuideRouteImport.update({
  id: '/do-business_/$guide',
  path: '/do-business/$guide',
  getParentRoute: () => rootRouteImport,
} as any)
const EgyptAppsCategoryRoute = EgyptAppsCategoryRouteImport.update({
  id: '/egypt-apps_/$category',
  path: '/egypt-apps/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const EgyptThroughTimeMilitaryHistoryRoute =
  EgyptThroughTimeMilitaryHistoryRouteImport.update({
    id: '/egypt-through-time_/military-history',
    path: '/egypt-through-time/military-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const EgyptianHeritageWorldwideIdRoute =
  EgyptianHeritageWorldwideIdRouteImport.update({
    id: '/egyptian-heritage-worldwide_/$id',
    path: '/egyptian-heritage-worldwide/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events_/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesTypeRoute = ExperiencesTypeRouteImport.update({
  id: '/experiences/$type',
  path: '/experiences/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentDirectoryDigitalServicesRoute =
  GovernmentDirectoryDigitalServicesRouteImport.update({
    id: '/government-directory_/digital-services',
    path: '/government-directory/digital-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const GovernoratesIndexRoute = GovernoratesIndexRouteImport.update({
  id: '/governorates/',
  path: '/governorates/',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernoratesIdRoute = GovernoratesIdRouteImport.update({
  id: '/governorates/$id',
  path: '/governorates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageSitesIdRoute = HeritageSitesIdRouteImport.update({
  id: '/heritage-sites_/$id',
  path: '/heritage-sites/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentOpportunitiesIdRoute =
  InvestmentOpportunitiesIdRouteImport.update({
    id: '/investment-opportunities_/$id',
    path: '/investment-opportunities/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConsentRoute = LegalConsentRouteImport.update({
  id: '/legal/consent',
  path: '/legal/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalReviewChecklistRoute = LegalReviewChecklistRouteImport.update({
  id: '/legal/review-checklist',
  path: '/legal/review-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveInEgyptGuideRoute = LiveInEgyptGuideRouteImport.update({
  id: '/live-in-egypt_/$guide',
  path: '/live-in-egypt/$guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveLikeAnEgyptianSectionRoute =
  LiveLikeAnEgyptianSectionRouteImport.update({
    id: '/live-like-an-egyptian_/$section',
    path: '/live-like-an-egyptian/$section',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceEgyptianCottonRoute =
  MarketplaceEgyptianCottonRouteImport.update({
    id: '/marketplace/egyptian-cotton',
    path: '/marketplace/egyptian-cotton',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceHandmadeCraftsRoute =
  MarketplaceHandmadeCraftsRouteImport.update({
    id: '/marketplace/handmade-crafts',
    path: '/marketplace/handmade-crafts',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceLocalProducersRoute =
  MarketplaceLocalProducersRouteImport.update({
    id: '/marketplace/local-producers',
    path: '/marketplace/local-producers',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceWearEgyptRoute = MarketplaceWearEgyptRouteImport.update({
  id: '/marketplace/wear-egypt',
  path: '/marketplace/wear-egypt',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseumsIdRoute = MuseumsIdRouteImport.update({
  id: '/museums_/$id',
  path: '/museums/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsIndexRoute = MyTripsIndexRouteImport.update({
  id: '/my-trips/',
  path: '/my-trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsNewRoute = MyTripsNewRouteImport.update({
  id: '/my-trips/new',
  path: '/my-trips/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIdRoute = OffersIdRouteImport.update({
  id: '/offers_/$id',
  path: '/offers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIdRoute = PlacesIdRouteImport.update({
  id: '/places/$id',
  path: '/places/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products_/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties_/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers_/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchProgramsIdRoute = ResearchProgramsIdRouteImport.update({
  id: '/research-programs_/$id',
  path: '/research-programs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelerStoriesIdRoute = TravelerStoriesIdRouteImport.update({
  id: '/traveler-stories_/$id',
  path: '/traveler-stories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIdRoute = TripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitEgyptEVisaRoute = VisitEgyptEVisaRouteImport.update({
  id: '/visit-egypt_/e-visa',
  path: '/visit-egypt/e-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitEgyptTravelAndTourismRoute =
  VisitEgyptTravelAndTourismRouteImport.update({
    id: '/visit-egypt_/travel-and-tourism',
    path: '/visit-egypt/travel-and-tourism',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentTableRoute = AdminContentTableRouteImport.update({
  id: '/content/$table',
  path: '/content/$table',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmInvestmentRoute = AdminCrmInvestmentRouteImport.update({
  id: '/crm/investment',
  path: '/crm/investment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmPropertiesRoute = AdminCrmPropertiesRouteImport.update({
  id: '/crm/properties',
  path: '/crm/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersNewRoute = AdminPartnersNewRouteImport.update({
  id: '/partners_/new',
  path: '/partners/new',
  getParentRoute: () => AdminRoute,
} as any)
const EgyptThroughTimeMilitaryHistoryFiguresRoute =
  EgyptThroughTimeMilitaryHistoryFiguresRouteImport.update({
    id: '/egypt-through-time_/military-history_/figures',
    path: '/egypt-through-time/military-history/figures',
    getParentRoute: () => rootRouteImport,
  } as any)
const EgyptThroughTimeMilitaryHistoryLibraryRoute =
  EgyptThroughTimeMilitaryHistoryLibraryRouteImport.update({
    id: '/egypt-through-time_/military-history_/library',
    path: '/egypt-through-time/military-history/library',
    getParentRoute: () => rootRouteImport,
  } as any)
const EgyptThroughTimeMilitaryHistoryMapRoute =
  EgyptThroughTimeMilitaryHistoryMapRouteImport.update({
    id: '/egypt-through-time_/military-history_/map',
    path: '/egypt-through-time/military-history/map',
    getParentRoute: () => rootRouteImport,
  } as any)
const EgyptThroughTimeMilitaryHistoryRecordsRoute =
  EgyptThroughTimeMilitaryHistoryRecordsRouteImport.update({
    id: '/egypt-through-time_/military-history_/records',
    path: '/egypt-through-time/military-history/records',
    getParentRoute: () => rootRouteImport,
  } as any)
const EgyptThroughTimeMilitaryHistoryTimelineRoute =
  EgyptThroughTimeMilitaryHistoryTimelineRouteImport.update({
    id: '/egypt-through-time_/military-history_/timeline',
    path: '/egypt-through-time/military-history/timeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const LiveLikeAnEgyptianSectionSlugRoute =
  LiveLikeAnEgyptianSectionSlugRouteImport.update({
    id: '/live-like-an-egyptian_/$section_/$slug',
    path: '/live-like-an-egyptian/$section/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const PartnersTypeIdRoute = PartnersTypeIdRouteImport.update({
  id: '/partners/$type/$id',
  path: '/partners/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProviderRoute = ApiPublicHooksProviderRouteImport.update({
  id: '/api/public/hooks/$provider',
  path: '/api/public/hooks/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const EgyptThroughTimeMilitaryHistoryFiguresSlugRoute =
  EgyptThroughTimeMilitaryHistoryFiguresSlugRouteImport.update({
    id: '/egypt-through-time_/military-history_/figures_/$slug',
    path: '/egypt-through-time/military-history/figures/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const EgyptThroughTimeMilitaryHistoryRecordsSlugRoute =
  EgyptThroughTimeMilitaryHistoryRecordsSlugRouteImport.update({
    id: '/egypt-through-time_/military-history_/records_/$slug',
    path: '/egypt-through-time/military-history/records/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/do-business': typeof DoBusinessRoute
  '/egypt-apps': typeof EgyptAppsRoute
  '/egypt-through-time': typeof EgyptThroughTimeRoute
  '/egyptian-heritage-worldwide': typeof EgyptianHeritageWorldwideRoute
  '/emergency-numbers': typeof EmergencyNumbersRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/events': typeof EventsRoute
  '/explore-egypt': typeof ExploreEgyptRoute
  '/faq': typeof FaqRoute
  '/government': typeof GovernmentRoute
  '/government-directory': typeof GovernmentDirectoryRoute
  '/heritage-sites': typeof HeritageSitesRoute
  '/invest-in-egypt': typeof InvestInEgyptRoute
  '/investment-opportunities': typeof InvestmentOpportunitiesRoute
  '/know-your-roots': typeof KnowYourRootsRoute
  '/live-in-egypt': typeof LiveInEgyptRoute
  '/live-like-an-egyptian': typeof LiveLikeAnEgyptianRoute
  '/museums': typeof MuseumsRoute
  '/offers': typeof OffersRoute
  '/our-mission': typeof OurMissionRoute
  '/photo-credits': typeof PhotoCreditsRoute
  '/products': typeof ProductsRoute
  '/properties': typeof PropertiesRoute
  '/providers': typeof ProvidersRoute
  '/real-estate': typeof RealEstateRoute
  '/research-programs': typeof ResearchProgramsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/traveler-stories': typeof TravelerStoriesRoute
  '/trust-center': typeof TrustCenterRoute
  '/vision-values': typeof VisionValuesRoute
  '/visit-egypt': typeof VisitEgyptRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/countries/$id': typeof CountriesIdRoute
  '/do-business/$guide': typeof DoBusinessGuideRoute
  '/egypt-apps/$category': typeof EgyptAppsCategoryRoute
  '/egypt-through-time/military-history': typeof EgyptThroughTimeMilitaryHistoryRoute
  '/egyptian-heritage-worldwide/$id': typeof EgyptianHeritageWorldwideIdRoute
  '/events/$id': typeof EventsIdRoute
  '/experiences/$type': typeof ExperiencesTypeRoute
  '/government-directory/digital-services': typeof GovernmentDirectoryDigitalServicesRoute
  '/governorates/$id': typeof GovernoratesIdRoute
  '/heritage-sites/$id': typeof HeritageSitesIdRoute
  '/investment-opportunities/$id': typeof InvestmentOpportunitiesIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/consent': typeof LegalConsentRoute
  '/legal/review-checklist': typeof LegalReviewChecklistRoute
  '/live-in-egypt/$guide': typeof LiveInEgyptGuideRoute
  '/live-like-an-egyptian/$section': typeof LiveLikeAnEgyptianSectionRoute
  '/marketplace/egyptian-cotton': typeof MarketplaceEgyptianCottonRoute
  '/marketplace/handmade-crafts': typeof MarketplaceHandmadeCraftsRoute
  '/marketplace/local-producers': typeof MarketplaceLocalProducersRoute
  '/marketplace/wear-egypt': typeof MarketplaceWearEgyptRoute
  '/museums/$id': typeof MuseumsIdRoute
  '/my-trips/new': typeof MyTripsNewRoute
  '/offers/$id': typeof OffersIdRoute
  '/places/$id': typeof PlacesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/research-programs/$id': typeof ResearchProgramsIdRoute
  '/traveler-stories/$id': typeof TravelerStoriesIdRoute
  '/trips/$id': typeof TripsIdRoute
  '/visit-egypt/e-visa': typeof VisitEgyptEVisaRoute
  '/visit-egypt/travel-and-tourism': typeof VisitEgyptTravelAndTourismRoute
  '/admin/': typeof AdminIndexRoute
  '/governorates/': typeof GovernoratesIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/my-trips/': typeof MyTripsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/admin/content/$table': typeof AdminContentTableRoute
  '/admin/crm/investment': typeof AdminCrmInvestmentRoute
  '/admin/crm/properties': typeof AdminCrmPropertiesRoute
  '/admin/partners/new': typeof AdminPartnersNewRoute
  '/egypt-through-time/military-history/figures': typeof EgyptThroughTimeMilitaryHistoryFiguresRoute
  '/egypt-through-time/military-history/library': typeof EgyptThroughTimeMilitaryHistoryLibraryRoute
  '/egypt-through-time/military-history/map': typeof EgyptThroughTimeMilitaryHistoryMapRoute
  '/egypt-through-time/military-history/records': typeof EgyptThroughTimeMilitaryHistoryRecordsRoute
  '/egypt-through-time/military-history/timeline': typeof EgyptThroughTimeMilitaryHistoryTimelineRoute
  '/live-like-an-egyptian/$section/$slug': typeof LiveLikeAnEgyptianSectionSlugRoute
  '/partners/$type/$id': typeof PartnersTypeIdRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/api/public/hooks/$provider': typeof ApiPublicHooksProviderRoute
  '/egypt-through-time/military-history/figures/$slug': typeof EgyptThroughTimeMilitaryHistoryFiguresSlugRoute
  '/egypt-through-time/military-history/records/$slug': typeof EgyptThroughTimeMilitaryHistoryRecordsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/do-business': typeof DoBusinessRoute
  '/egypt-apps': typeof EgyptAppsRoute
  '/egypt-through-time': typeof EgyptThroughTimeRoute
  '/egyptian-heritage-worldwide': typeof EgyptianHeritageWorldwideRoute
  '/emergency-numbers': typeof EmergencyNumbersRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/events': typeof EventsRoute
  '/explore-egypt': typeof ExploreEgyptRoute
  '/faq': typeof FaqRoute
  '/government': typeof GovernmentRoute
  '/government-directory': typeof GovernmentDirectoryRoute
  '/heritage-sites': typeof HeritageSitesRoute
  '/invest-in-egypt': typeof InvestInEgyptRoute
  '/investment-opportunities': typeof InvestmentOpportunitiesRoute
  '/know-your-roots': typeof KnowYourRootsRoute
  '/live-in-egypt': typeof LiveInEgyptRoute
  '/live-like-an-egyptian': typeof LiveLikeAnEgyptianRoute
  '/museums': typeof MuseumsRoute
  '/offers': typeof OffersRoute
  '/our-mission': typeof OurMissionRoute
  '/photo-credits': typeof PhotoCreditsRoute
  '/products': typeof ProductsRoute
  '/properties': typeof PropertiesRoute
  '/providers': typeof ProvidersRoute
  '/real-estate': typeof RealEstateRoute
  '/research-programs': typeof ResearchProgramsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/traveler-stories': typeof TravelerStoriesRoute
  '/trust-center': typeof TrustCenterRoute
  '/vision-values': typeof VisionValuesRoute
  '/visit-egypt': typeof VisitEgyptRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/countries/$id': typeof CountriesIdRoute
  '/do-business/$guide': typeof DoBusinessGuideRoute
  '/egypt-apps/$category': typeof EgyptAppsCategoryRoute
  '/egypt-through-time/military-history': typeof EgyptThroughTimeMilitaryHistoryRoute
  '/egyptian-heritage-worldwide/$id': typeof EgyptianHeritageWorldwideIdRoute
  '/events/$id': typeof EventsIdRoute
  '/experiences/$type': typeof ExperiencesTypeRoute
  '/government-directory/digital-services': typeof GovernmentDirectoryDigitalServicesRoute
  '/governorates/$id': typeof GovernoratesIdRoute
  '/heritage-sites/$id': typeof HeritageSitesIdRoute
  '/investment-opportunities/$id': typeof InvestmentOpportunitiesIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/consent': typeof LegalConsentRoute
  '/legal/review-checklist': typeof LegalReviewChecklistRoute
  '/live-in-egypt/$guide': typeof LiveInEgyptGuideRoute
  '/live-like-an-egyptian/$section': typeof LiveLikeAnEgyptianSectionRoute
  '/marketplace/egyptian-cotton': typeof MarketplaceEgyptianCottonRoute
  '/marketplace/handmade-crafts': typeof MarketplaceHandmadeCraftsRoute
  '/marketplace/local-producers': typeof MarketplaceLocalProducersRoute
  '/marketplace/wear-egypt': typeof MarketplaceWearEgyptRoute
  '/museums/$id': typeof MuseumsIdRoute
  '/my-trips/new': typeof MyTripsNewRoute
  '/offers/$id': typeof OffersIdRoute
  '/places/$id': typeof PlacesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/research-programs/$id': typeof ResearchProgramsIdRoute
  '/traveler-stories/$id': typeof TravelerStoriesIdRoute
  '/trips/$id': typeof TripsIdRoute
  '/visit-egypt/e-visa': typeof VisitEgyptEVisaRoute
  '/visit-egypt/travel-and-tourism': typeof VisitEgyptTravelAndTourismRoute
  '/admin': typeof AdminIndexRoute
  '/governorates': typeof GovernoratesIndexRoute
  '/legal': typeof LegalIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/my-trips': typeof MyTripsIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/admin/content/$table': typeof AdminContentTableRoute
  '/admin/crm/investment': typeof AdminCrmInvestmentRoute
  '/admin/crm/properties': typeof AdminCrmPropertiesRoute
  '/admin/partners/new': typeof AdminPartnersNewRoute
  '/egypt-through-time/military-history/figures': typeof EgyptThroughTimeMilitaryHistoryFiguresRoute
  '/egypt-through-time/military-history/library': typeof EgyptThroughTimeMilitaryHistoryLibraryRoute
  '/egypt-through-time/military-history/map': typeof EgyptThroughTimeMilitaryHistoryMapRoute
  '/egypt-through-time/military-history/records': typeof EgyptThroughTimeMilitaryHistoryRecordsRoute
  '/egypt-through-time/military-history/timeline': typeof EgyptThroughTimeMilitaryHistoryTimelineRoute
  '/live-like-an-egyptian/$section/$slug': typeof LiveLikeAnEgyptianSectionSlugRoute
  '/partners/$type/$id': typeof PartnersTypeIdRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/api/public/hooks/$provider': typeof ApiPublicHooksProviderRoute
  '/egypt-through-time/military-history/figures/$slug': typeof EgyptThroughTimeMilitaryHistoryFiguresSlugRoute
  '/egypt-through-time/military-history/records/$slug': typeof EgyptThroughTimeMilitaryHistoryRecordsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/do-business': typeof DoBusinessRoute
  '/egypt-apps': typeof EgyptAppsRoute
  '/egypt-through-time': typeof EgyptThroughTimeRoute
  '/egyptian-heritage-worldwide': typeof EgyptianHeritageWorldwideRoute
  '/emergency-numbers': typeof EmergencyNumbersRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/events': typeof EventsRoute
  '/explore-egypt': typeof ExploreEgyptRoute
  '/faq': typeof FaqRoute
  '/government': typeof GovernmentRoute
  '/government-directory': typeof GovernmentDirectoryRoute
  '/heritage-sites': typeof HeritageSitesRoute
  '/invest-in-egypt': typeof InvestInEgyptRoute
  '/investment-opportunities': typeof InvestmentOpportunitiesRoute
  '/know-your-roots': typeof KnowYourRootsRoute
  '/live-in-egypt': typeof LiveInEgyptRoute
  '/live-like-an-egyptian': typeof LiveLikeAnEgyptianRoute
  '/museums': typeof MuseumsRoute
  '/offers': typeof OffersRoute
  '/our-mission': typeof OurMissionRoute
  '/photo-credits': typeof PhotoCreditsRoute
  '/products': typeof ProductsRoute
  '/properties': typeof PropertiesRoute
  '/providers': typeof ProvidersRoute
  '/real-estate': typeof RealEstateRoute
  '/research-programs': typeof ResearchProgramsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/traveler-stories': typeof TravelerStoriesRoute
  '/trust-center': typeof TrustCenterRoute
  '/vision-values': typeof VisionValuesRoute
  '/visit-egypt': typeof VisitEgyptRoute
  '/account_/bookings': typeof AccountBookingsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/countries_/$id': typeof CountriesIdRoute
  '/do-business_/$guide': typeof DoBusinessGuideRoute
  '/egypt-apps_/$category': typeof EgyptAppsCategoryRoute
  '/egypt-through-time_/military-history': typeof EgyptThroughTimeMilitaryHistoryRoute
  '/egyptian-heritage-worldwide_/$id': typeof EgyptianHeritageWorldwideIdRoute
  '/events_/$id': typeof EventsIdRoute
  '/experiences/$type': typeof ExperiencesTypeRoute
  '/government-directory_/digital-services': typeof GovernmentDirectoryDigitalServicesRoute
  '/governorates/$id': typeof GovernoratesIdRoute
  '/heritage-sites_/$id': typeof HeritageSitesIdRoute
  '/investment-opportunities_/$id': typeof InvestmentOpportunitiesIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/consent': typeof LegalConsentRoute
  '/legal/review-checklist': typeof LegalReviewChecklistRoute
  '/live-in-egypt_/$guide': typeof LiveInEgyptGuideRoute
  '/live-like-an-egyptian_/$section': typeof LiveLikeAnEgyptianSectionRoute
  '/marketplace/egyptian-cotton': typeof MarketplaceEgyptianCottonRoute
  '/marketplace/handmade-crafts': typeof MarketplaceHandmadeCraftsRoute
  '/marketplace/local-producers': typeof MarketplaceLocalProducersRoute
  '/marketplace/wear-egypt': typeof MarketplaceWearEgyptRoute
  '/museums_/$id': typeof MuseumsIdRoute
  '/my-trips/new': typeof MyTripsNewRoute
  '/offers_/$id': typeof OffersIdRoute
  '/places/$id': typeof PlacesIdRoute
  '/products_/$id': typeof ProductsIdRoute
  '/properties_/$id': typeof PropertiesIdRoute
  '/providers_/$id': typeof ProvidersIdRoute
  '/research-programs_/$id': typeof ResearchProgramsIdRoute
  '/traveler-stories_/$id': typeof TravelerStoriesIdRoute
  '/trips/$id': typeof TripsIdRoute
  '/visit-egypt_/e-visa': typeof VisitEgyptEVisaRoute
  '/visit-egypt_/travel-and-tourism': typeof VisitEgyptTravelAndTourismRoute
  '/admin/': typeof AdminIndexRoute
  '/governorates/': typeof GovernoratesIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/my-trips/': typeof MyTripsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/admin/content/$table': typeof AdminContentTableRoute
  '/admin/crm/investment': typeof AdminCrmInvestmentRoute
  '/admin/crm/properties': typeof AdminCrmPropertiesRoute
  '/admin/partners_/new': typeof AdminPartnersNewRoute
  '/egypt-through-time_/military-history_/figures': typeof EgyptThroughTimeMilitaryHistoryFiguresRoute
  '/egypt-through-time_/military-history_/library': typeof EgyptThroughTimeMilitaryHistoryLibraryRoute
  '/egypt-through-time_/military-history_/map': typeof EgyptThroughTimeMilitaryHistoryMapRoute
  '/egypt-through-time_/military-history_/records': typeof EgyptThroughTimeMilitaryHistoryRecordsRoute
  '/egypt-through-time_/military-history_/timeline': typeof EgyptThroughTimeMilitaryHistoryTimelineRoute
  '/live-like-an-egyptian_/$section_/$slug': typeof LiveLikeAnEgyptianSectionSlugRoute
  '/partners/$type/$id': typeof PartnersTypeIdRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/api/public/hooks/$provider': typeof ApiPublicHooksProviderRoute
  '/egypt-through-time_/military-history_/figures_/$slug': typeof EgyptThroughTimeMilitaryHistoryFiguresSlugRoute
  '/egypt-through-time_/military-history_/records_/$slug': typeof EgyptThroughTimeMilitaryHistoryRecordsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/become-a-partner'
    | '/contact'
    | '/countries'
    | '/do-business'
    | '/egypt-apps'
    | '/egypt-through-time'
    | '/egyptian-heritage-worldwide'
    | '/emergency-numbers'
    | '/encyclopedia'
    | '/events'
    | '/explore-egypt'
    | '/faq'
    | '/government'
    | '/government-directory'
    | '/heritage-sites'
    | '/invest-in-egypt'
    | '/investment-opportunities'
    | '/know-your-roots'
    | '/live-in-egypt'
    | '/live-like-an-egyptian'
    | '/museums'
    | '/offers'
    | '/our-mission'
    | '/photo-credits'
    | '/products'
    | '/properties'
    | '/providers'
    | '/real-estate'
    | '/research-programs'
    | '/saved'
    | '/search'
    | '/traveler-stories'
    | '/trust-center'
    | '/vision-values'
    | '/visit-egypt'
    | '/account/bookings'
    | '/admin/bookings'
    | '/admin/integrations'
    | '/admin/maintenance'
    | '/admin/partners'
    | '/admin/users'
    | '/api/concierge'
    | '/countries/$id'
    | '/do-business/$guide'
    | '/egypt-apps/$category'
    | '/egypt-through-time/military-history'
    | '/egyptian-heritage-worldwide/$id'
    | '/events/$id'
    | '/experiences/$type'
    | '/government-directory/digital-services'
    | '/governorates/$id'
    | '/heritage-sites/$id'
    | '/investment-opportunities/$id'
    | '/legal/$slug'
    | '/legal/consent'
    | '/legal/review-checklist'
    | '/live-in-egypt/$guide'
    | '/live-like-an-egyptian/$section'
    | '/marketplace/egyptian-cotton'
    | '/marketplace/handmade-crafts'
    | '/marketplace/local-producers'
    | '/marketplace/wear-egypt'
    | '/museums/$id'
    | '/my-trips/new'
    | '/offers/$id'
    | '/places/$id'
    | '/products/$id'
    | '/properties/$id'
    | '/providers/$id'
    | '/research-programs/$id'
    | '/traveler-stories/$id'
    | '/trips/$id'
    | '/visit-egypt/e-visa'
    | '/visit-egypt/travel-and-tourism'
    | '/admin/'
    | '/governorates/'
    | '/legal/'
    | '/marketplace/'
    | '/my-trips/'
    | '/partners/'
    | '/admin/content/$table'
    | '/admin/crm/investment'
    | '/admin/crm/properties'
    | '/admin/partners/new'
    | '/egypt-through-time/military-history/figures'
    | '/egypt-through-time/military-history/library'
    | '/egypt-through-time/military-history/map'
    | '/egypt-through-time/military-history/records'
    | '/egypt-through-time/military-history/timeline'
    | '/live-like-an-egyptian/$section/$slug'
    | '/partners/$type/$id'
    | '/admin/content/'
    | '/api/public/hooks/$provider'
    | '/egypt-through-time/military-history/figures/$slug'
    | '/egypt-through-time/military-history/records/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/become-a-partner'
    | '/contact'
    | '/countries'
    | '/do-business'
    | '/egypt-apps'
    | '/egypt-through-time'
    | '/egyptian-heritage-worldwide'
    | '/emergency-numbers'
    | '/encyclopedia'
    | '/events'
    | '/explore-egypt'
    | '/faq'
    | '/government'
    | '/government-directory'
    | '/heritage-sites'
    | '/invest-in-egypt'
    | '/investment-opportunities'
    | '/know-your-roots'
    | '/live-in-egypt'
    | '/live-like-an-egyptian'
    | '/museums'
    | '/offers'
    | '/our-mission'
    | '/photo-credits'
    | '/products'
    | '/properties'
    | '/providers'
    | '/real-estate'
    | '/research-programs'
    | '/saved'
    | '/search'
    | '/traveler-stories'
    | '/trust-center'
    | '/vision-values'
    | '/visit-egypt'
    | '/account/bookings'
    | '/admin/bookings'
    | '/admin/integrations'
    | '/admin/maintenance'
    | '/admin/partners'
    | '/admin/users'
    | '/api/concierge'
    | '/countries/$id'
    | '/do-business/$guide'
    | '/egypt-apps/$category'
    | '/egypt-through-time/military-history'
    | '/egyptian-heritage-worldwide/$id'
    | '/events/$id'
    | '/experiences/$type'
    | '/government-directory/digital-services'
    | '/governorates/$id'
    | '/heritage-sites/$id'
    | '/investment-opportunities/$id'
    | '/legal/$slug'
    | '/legal/consent'
    | '/legal/review-checklist'
    | '/live-in-egypt/$guide'
    | '/live-like-an-egyptian/$section'
    | '/marketplace/egyptian-cotton'
    | '/marketplace/handmade-crafts'
    | '/marketplace/local-producers'
    | '/marketplace/wear-egypt'
    | '/museums/$id'
    | '/my-trips/new'
    | '/offers/$id'
    | '/places/$id'
    | '/products/$id'
    | '/properties/$id'
    | '/providers/$id'
    | '/research-programs/$id'
    | '/traveler-stories/$id'
    | '/trips/$id'
    | '/visit-egypt/e-visa'
    | '/visit-egypt/travel-and-tourism'
    | '/admin'
    | '/governorates'
    | '/legal'
    | '/marketplace'
    | '/my-trips'
    | '/partners'
    | '/admin/content/$table'
    | '/admin/crm/investment'
    | '/admin/crm/properties'
    | '/admin/partners/new'
    | '/egypt-through-time/military-history/figures'
    | '/egypt-through-time/military-history/library'
    | '/egypt-through-time/military-history/map'
    | '/egypt-through-time/military-history/records'
    | '/egypt-through-time/military-history/timeline'
    | '/live-like-an-egyptian/$section/$slug'
    | '/partners/$type/$id'
    | '/admin/content'
    | '/api/public/hooks/$provider'
    | '/egypt-through-time/military-history/figures/$slug'
    | '/egypt-through-time/military-history/records/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/become-a-partner'
    | '/contact'
    | '/countries'
    | '/do-business'
    | '/egypt-apps'
    | '/egypt-through-time'
    | '/egyptian-heritage-worldwide'
    | '/emergency-numbers'
    | '/encyclopedia'
    | '/events'
    | '/explore-egypt'
    | '/faq'
    | '/government'
    | '/government-directory'
    | '/heritage-sites'
    | '/invest-in-egypt'
    | '/investment-opportunities'
    | '/know-your-roots'
    | '/live-in-egypt'
    | '/live-like-an-egyptian'
    | '/museums'
    | '/offers'
    | '/our-mission'
    | '/photo-credits'
    | '/products'
    | '/properties'
    | '/providers'
    | '/real-estate'
    | '/research-programs'
    | '/saved'
    | '/search'
    | '/traveler-stories'
    | '/trust-center'
    | '/vision-values'
    | '/visit-egypt'
    | '/account_/bookings'
    | '/admin/bookings'
    | '/admin/integrations'
    | '/admin/maintenance'
    | '/admin/partners'
    | '/admin/users'
    | '/api/concierge'
    | '/countries_/$id'
    | '/do-business_/$guide'
    | '/egypt-apps_/$category'
    | '/egypt-through-time_/military-history'
    | '/egyptian-heritage-worldwide_/$id'
    | '/events_/$id'
    | '/experiences/$type'
    | '/government-directory_/digital-services'
    | '/governorates/$id'
    | '/heritage-sites_/$id'
    | '/investment-opportunities_/$id'
    | '/legal/$slug'
    | '/legal/consent'
    | '/legal/review-checklist'
    | '/live-in-egypt_/$guide'
    | '/live-like-an-egyptian_/$section'
    | '/marketplace/egyptian-cotton'
    | '/marketplace/handmade-crafts'
    | '/marketplace/local-producers'
    | '/marketplace/wear-egypt'
    | '/museums_/$id'
    | '/my-trips/new'
    | '/offers_/$id'
    | '/places/$id'
    | '/products_/$id'
    | '/properties_/$id'
    | '/providers_/$id'
    | '/research-programs_/$id'
    | '/traveler-stories_/$id'
    | '/trips/$id'
    | '/visit-egypt_/e-visa'
    | '/visit-egypt_/travel-and-tourism'
    | '/admin/'
    | '/governorates/'
    | '/legal/'
    | '/marketplace/'
    | '/my-trips/'
    | '/partners/'
    | '/admin/content/$table'
    | '/admin/crm/investment'
    | '/admin/crm/properties'
    | '/admin/partners_/new'
    | '/egypt-through-time_/military-history_/figures'
    | '/egypt-through-time_/military-history_/library'
    | '/egypt-through-time_/military-history_/map'
    | '/egypt-through-time_/military-history_/records'
    | '/egypt-through-time_/military-history_/timeline'
    | '/live-like-an-egyptian_/$section_/$slug'
    | '/partners/$type/$id'
    | '/admin/content/'
    | '/api/public/hooks/$provider'
    | '/egypt-through-time_/military-history_/figures_/$slug'
    | '/egypt-through-time_/military-history_/records_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeAPartnerRoute: typeof BecomeAPartnerRoute
  ContactRoute: typeof ContactRoute
  CountriesRoute: typeof CountriesRoute
  DoBusinessRoute: typeof DoBusinessRoute
  EgyptAppsRoute: typeof EgyptAppsRoute
  EgyptThroughTimeRoute: typeof EgyptThroughTimeRoute
  EgyptianHeritageWorldwideRoute: typeof EgyptianHeritageWorldwideRoute
  EmergencyNumbersRoute: typeof EmergencyNumbersRoute
  EncyclopediaRoute: typeof EncyclopediaRoute
  EventsRoute: typeof EventsRoute
  ExploreEgyptRoute: typeof ExploreEgyptRoute
  FaqRoute: typeof FaqRoute
  GovernmentRoute: typeof GovernmentRoute
  GovernmentDirectoryRoute: typeof GovernmentDirectoryRoute
  HeritageSitesRoute: typeof HeritageSitesRoute
  InvestInEgyptRoute: typeof InvestInEgyptRoute
  InvestmentOpportunitiesRoute: typeof InvestmentOpportunitiesRoute
  KnowYourRootsRoute: typeof KnowYourRootsRoute
  LiveInEgyptRoute: typeof LiveInEgyptRoute
  LiveLikeAnEgyptianRoute: typeof LiveLikeAnEgyptianRoute
  MuseumsRoute: typeof MuseumsRoute
  OffersRoute: typeof OffersRoute
  OurMissionRoute: typeof OurMissionRoute
  PhotoCreditsRoute: typeof PhotoCreditsRoute
  ProductsRoute: typeof ProductsRoute
  PropertiesRoute: typeof PropertiesRoute
  ProvidersRoute: typeof ProvidersRoute
  RealEstateRoute: typeof RealEstateRoute
  ResearchProgramsRoute: typeof ResearchProgramsRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  TravelerStoriesRoute: typeof TravelerStoriesRoute
  TrustCenterRoute: typeof TrustCenterRoute
  VisionValuesRoute: typeof VisionValuesRoute
  VisitEgyptRoute: typeof VisitEgyptRoute
  AccountBookingsRoute: typeof AccountBookingsRoute
  ApiConciergeRoute: typeof ApiConciergeRoute
  CountriesIdRoute: typeof CountriesIdRoute
  DoBusinessGuideRoute: typeof DoBusinessGuideRoute
  EgyptAppsCategoryRoute: typeof EgyptAppsCategoryRoute
  EgyptThroughTimeMilitaryHistoryRoute: typeof EgyptThroughTimeMilitaryHistoryRoute
  EgyptianHeritageWorldwideIdRoute: typeof EgyptianHeritageWorldwideIdRoute
  EventsIdRoute: typeof EventsIdRoute
  ExperiencesTypeRoute: typeof ExperiencesTypeRoute
  GovernmentDirectoryDigitalServicesRoute: typeof GovernmentDirectoryDigitalServicesRoute
  GovernoratesIdRoute: typeof GovernoratesIdRoute
  HeritageSitesIdRoute: typeof HeritageSitesIdRoute
  InvestmentOpportunitiesIdRoute: typeof InvestmentOpportunitiesIdRoute
  LegalSlugRoute: typeof LegalSlugRoute
  LegalConsentRoute: typeof LegalConsentRoute
  LegalReviewChecklistRoute: typeof LegalReviewChecklistRoute
  LiveInEgyptGuideRoute: typeof LiveInEgyptGuideRoute
  LiveLikeAnEgyptianSectionRoute: typeof LiveLikeAnEgyptianSectionRoute
  MarketplaceEgyptianCottonRoute: typeof MarketplaceEgyptianCottonRoute
  MarketplaceHandmadeCraftsRoute: typeof MarketplaceHandmadeCraftsRoute
  MarketplaceLocalProducersRoute: typeof MarketplaceLocalProducersRoute
  MarketplaceWearEgyptRoute: typeof MarketplaceWearEgyptRoute
  MuseumsIdRoute: typeof MuseumsIdRoute
  MyTripsNewRoute: typeof MyTripsNewRoute
  OffersIdRoute: typeof OffersIdRoute
  PlacesIdRoute: typeof PlacesIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
  ResearchProgramsIdRoute: typeof ResearchProgramsIdRoute
  TravelerStoriesIdRoute: typeof TravelerStoriesIdRoute
  TripsIdRoute: typeof TripsIdRoute
  VisitEgyptEVisaRoute: typeof VisitEgyptEVisaRoute
  VisitEgyptTravelAndTourismRoute: typeof VisitEgyptTravelAndTourismRoute
  GovernoratesIndexRoute: typeof GovernoratesIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MyTripsIndexRoute: typeof MyTripsIndexRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
  EgyptThroughTimeMilitaryHistoryFiguresRoute: typeof EgyptThroughTimeMilitaryHistoryFiguresRoute
  EgyptThroughTimeMilitaryHistoryLibraryRoute: typeof EgyptThroughTimeMilitaryHistoryLibraryRoute
  EgyptThroughTimeMilitaryHistoryMapRoute: typeof EgyptThroughTimeMilitaryHistoryMapRoute
  EgyptThroughTimeMilitaryHistoryRecordsRoute: typeof EgyptThroughTimeMilitaryHistoryRecordsRoute
  EgyptThroughTimeMilitaryHistoryTimelineRoute: typeof EgyptThroughTimeMilitaryHistoryTimelineRoute
  LiveLikeAnEgyptianSectionSlugRoute: typeof LiveLikeAnEgyptianSectionSlugRoute
  PartnersTypeIdRoute: typeof PartnersTypeIdRoute
  ApiPublicHooksProviderRoute: typeof ApiPublicHooksProviderRoute
  EgyptThroughTimeMilitaryHistoryFiguresSlugRoute: typeof EgyptThroughTimeMilitaryHistoryFiguresSlugRoute
  EgyptThroughTimeMilitaryHistoryRecordsSlugRoute: typeof EgyptThroughTimeMilitaryHistoryRecordsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-partner': {
      id: '/become-a-partner'
      path: '/become-a-partner'
      fullPath: '/become-a-partner'
      preLoaderRoute: typeof BecomeAPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/do-business': {
      id: '/do-business'
      path: '/do-business'
      fullPath: '/do-business'
      preLoaderRoute: typeof DoBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egypt-apps': {
      id: '/egypt-apps'
      path: '/egypt-apps'
      fullPath: '/egypt-apps'
      preLoaderRoute: typeof EgyptAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egypt-through-time': {
      id: '/egypt-through-time'
      path: '/egypt-through-time'
      fullPath: '/egypt-through-time'
      preLoaderRoute: typeof EgyptThroughTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egyptian-heritage-worldwide': {
      id: '/egyptian-heritage-worldwide'
      path: '/egyptian-heritage-worldwide'
      fullPath: '/egyptian-heritage-worldwide'
      preLoaderRoute: typeof EgyptianHeritageWorldwideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-numbers': {
      id: '/emergency-numbers'
      path: '/emergency-numbers'
      fullPath: '/emergency-numbers'
      preLoaderRoute: typeof EmergencyNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encyclopedia': {
      id: '/encyclopedia'
      path: '/encyclopedia'
      fullPath: '/encyclopedia'
      preLoaderRoute: typeof EncyclopediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore-egypt': {
      id: '/explore-egypt'
      path: '/explore-egypt'
      fullPath: '/explore-egypt'
      preLoaderRoute: typeof ExploreEgyptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government-directory': {
      id: '/government-directory'
      path: '/government-directory'
      fullPath: '/government-directory'
      preLoaderRoute: typeof GovernmentDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage-sites': {
      id: '/heritage-sites'
      path: '/heritage-sites'
      fullPath: '/heritage-sites'
      preLoaderRoute: typeof HeritageSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest-in-egypt': {
      id: '/invest-in-egypt'
      path: '/invest-in-egypt'
      fullPath: '/invest-in-egypt'
      preLoaderRoute: typeof InvestInEgyptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-opportunities': {
      id: '/investment-opportunities'
      path: '/investment-opportunities'
      fullPath: '/investment-opportunities'
      preLoaderRoute: typeof InvestmentOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/know-your-roots': {
      id: '/know-your-roots'
      path: '/know-your-roots'
      fullPath: '/know-your-roots'
      preLoaderRoute: typeof KnowYourRootsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-in-egypt': {
      id: '/live-in-egypt'
      path: '/live-in-egypt'
      fullPath: '/live-in-egypt'
      preLoaderRoute: typeof LiveInEgyptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-like-an-egyptian': {
      id: '/live-like-an-egyptian'
      path: '/live-like-an-egyptian'
      fullPath: '/live-like-an-egyptian'
      preLoaderRoute: typeof LiveLikeAnEgyptianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/museums': {
      id: '/museums'
      path: '/museums'
      fullPath: '/museums'
      preLoaderRoute: typeof MuseumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-mission': {
      id: '/our-mission'
      path: '/our-mission'
      fullPath: '/our-mission'
      preLoaderRoute: typeof OurMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-credits': {
      id: '/photo-credits'
      path: '/photo-credits'
      fullPath: '/photo-credits'
      preLoaderRoute: typeof PhotoCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-programs': {
      id: '/research-programs'
      path: '/research-programs'
      fullPath: '/research-programs'
      preLoaderRoute: typeof ResearchProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traveler-stories': {
      id: '/traveler-stories'
      path: '/traveler-stories'
      fullPath: '/traveler-stories'
      preLoaderRoute: typeof TravelerStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-center': {
      id: '/trust-center'
      path: '/trust-center'
      fullPath: '/trust-center'
      preLoaderRoute: typeof TrustCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision-values': {
      id: '/vision-values'
      path: '/vision-values'
      fullPath: '/vision-values'
      preLoaderRoute: typeof VisionValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit-egypt': {
      id: '/visit-egypt'
      path: '/visit-egypt'
      fullPath: '/visit-egypt'
      preLoaderRoute: typeof VisitEgyptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/bookings': {
      id: '/account_/bookings'
      path: '/account/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AccountBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/concierge': {
      id: '/api/concierge'
      path: '/api/concierge'
      fullPath: '/api/concierge'
      preLoaderRoute: typeof ApiConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries_/$id': {
      id: '/countries_/$id'
      path: '/countries/$id'
      fullPath: '/countries/$id'
      preLoaderRoute: typeof CountriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/do-business_/$guide': {
      id: '/do-business_/$guide'
      path: '/do-business/$guide'
      fullPath: '/do-business/$guide'
      preLoaderRoute: typeof DoBusinessGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egypt-apps_/$category': {
      id: '/egypt-apps_/$category'
      path: '/egypt-apps/$category'
      fullPath: '/egypt-apps/$category'
      preLoaderRoute: typeof EgyptAppsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egypt-through-time_/military-history': {
      id: '/egypt-through-time_/military-history'
      path: '/egypt-through-time/military-history'
      fullPath: '/egypt-through-time/military-history'
      preLoaderRoute: typeof EgyptThroughTimeMilitaryHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egyptian-heritage-worldwide_/$id': {
      id: '/egyptian-heritage-worldwide_/$id'
      path: '/egyptian-heritage-worldwide/$id'
      fullPath: '/egyptian-heritage-worldwide/$id'
      preLoaderRoute: typeof EgyptianHeritageWorldwideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$id': {
      id: '/events_/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$type': {
      id: '/experiences/$type'
      path: '/experiences/$type'
      fullPath: '/experiences/$type'
      preLoaderRoute: typeof ExperiencesTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government-directory_/digital-services': {
      id: '/government-directory_/digital-services'
      path: '/government-directory/digital-services'
      fullPath: '/government-directory/digital-services'
      preLoaderRoute: typeof GovernmentDirectoryDigitalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governorates/': {
      id: '/governorates/'
      path: '/governorates'
      fullPath: '/governorates/'
      preLoaderRoute: typeof GovernoratesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governorates/$id': {
      id: '/governorates/$id'
      path: '/governorates/$id'
      fullPath: '/governorates/$id'
      preLoaderRoute: typeof GovernoratesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage-sites_/$id': {
      id: '/heritage-sites_/$id'
      path: '/heritage-sites/$id'
      fullPath: '/heritage-sites/$id'
      preLoaderRoute: typeof HeritageSitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-opportunities_/$id': {
      id: '/investment-opportunities_/$id'
      path: '/investment-opportunities/$id'
      fullPath: '/investment-opportunities/$id'
      preLoaderRoute: typeof InvestmentOpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/consent': {
      id: '/legal/consent'
      path: '/legal/consent'
      fullPath: '/legal/consent'
      preLoaderRoute: typeof LegalConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/review-checklist': {
      id: '/legal/review-checklist'
      path: '/legal/review-checklist'
      fullPath: '/legal/review-checklist'
      preLoaderRoute: typeof LegalReviewChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-in-egypt_/$guide': {
      id: '/live-in-egypt_/$guide'
      path: '/live-in-egypt/$guide'
      fullPath: '/live-in-egypt/$guide'
      preLoaderRoute: typeof LiveInEgyptGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-like-an-egyptian_/$section': {
      id: '/live-like-an-egyptian_/$section'
      path: '/live-like-an-egyptian/$section'
      fullPath: '/live-like-an-egyptian/$section'
      preLoaderRoute: typeof LiveLikeAnEgyptianSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/egyptian-cotton': {
      id: '/marketplace/egyptian-cotton'
      path: '/marketplace/egyptian-cotton'
      fullPath: '/marketplace/egyptian-cotton'
      preLoaderRoute: typeof MarketplaceEgyptianCottonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/handmade-crafts': {
      id: '/marketplace/handmade-crafts'
      path: '/marketplace/handmade-crafts'
      fullPath: '/marketplace/handmade-crafts'
      preLoaderRoute: typeof MarketplaceHandmadeCraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/local-producers': {
      id: '/marketplace/local-producers'
      path: '/marketplace/local-producers'
      fullPath: '/marketplace/local-producers'
      preLoaderRoute: typeof MarketplaceLocalProducersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/wear-egypt': {
      id: '/marketplace/wear-egypt'
      path: '/marketplace/wear-egypt'
      fullPath: '/marketplace/wear-egypt'
      preLoaderRoute: typeof MarketplaceWearEgyptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/museums_/$id': {
      id: '/museums_/$id'
      path: '/museums/$id'
      fullPath: '/museums/$id'
      preLoaderRoute: typeof MuseumsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips/': {
      id: '/my-trips/'
      path: '/my-trips'
      fullPath: '/my-trips/'
      preLoaderRoute: typeof MyTripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips/new': {
      id: '/my-trips/new'
      path: '/my-trips/new'
      fullPath: '/my-trips/new'
      preLoaderRoute: typeof MyTripsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers_/$id': {
      id: '/offers_/$id'
      path: '/offers/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof OffersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$id': {
      id: '/places/$id'
      path: '/places/$id'
      fullPath: '/places/$id'
      preLoaderRoute: typeof PlacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$id': {
      id: '/products_/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties_/$id': {
      id: '/properties_/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers_/$id': {
      id: '/providers_/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-programs_/$id': {
      id: '/research-programs_/$id'
      path: '/research-programs/$id'
      fullPath: '/research-programs/$id'
      preLoaderRoute: typeof ResearchProgramsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traveler-stories_/$id': {
      id: '/traveler-stories_/$id'
      path: '/traveler-stories/$id'
      fullPath: '/traveler-stories/$id'
      preLoaderRoute: typeof TravelerStoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$id': {
      id: '/trips/$id'
      path: '/trips/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof TripsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit-egypt_/e-visa': {
      id: '/visit-egypt_/e-visa'
      path: '/visit-egypt/e-visa'
      fullPath: '/visit-egypt/e-visa'
      preLoaderRoute: typeof VisitEgyptEVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit-egypt_/travel-and-tourism': {
      id: '/visit-egypt_/travel-and-tourism'
      path: '/visit-egypt/travel-and-tourism'
      fullPath: '/visit-egypt/travel-and-tourism'
      preLoaderRoute: typeof VisitEgyptTravelAndTourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/$table': {
      id: '/admin/content/$table'
      path: '/content/$table'
      fullPath: '/admin/content/$table'
      preLoaderRoute: typeof AdminContentTableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm/investment': {
      id: '/admin/crm/investment'
      path: '/crm/investment'
      fullPath: '/admin/crm/investment'
      preLoaderRoute: typeof AdminCrmInvestmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm/properties': {
      id: '/admin/crm/properties'
      path: '/crm/properties'
      fullPath: '/admin/crm/properties'
      preLoaderRoute: typeof AdminCrmPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners_/new': {
      id: '/admin/partners_/new'
      path: '/partners/new'
      fullPath: '/admin/partners/new'
      preLoaderRoute: typeof AdminPartnersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/egypt-through-time_/military-history_/figures': {
      id: '/egypt-through-time_/military-history_/figures'
      path: '/egypt-through-time/military-history/figures'
      fullPath: '/egypt-through-time/military-history/figures'
      preLoaderRoute: typeof EgyptThroughTimeMilitaryHistoryFiguresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egypt-through-time_/military-history_/library': {
      id: '/egypt-through-time_/military-history_/library'
      path: '/egypt-through-time/military-history/library'
      fullPath: '/egypt-through-time/military-history/library'
      preLoaderRoute: typeof EgyptThroughTimeMilitaryHistoryLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egypt-through-time_/military-history_/map': {
      id: '/egypt-through-time_/military-history_/map'
      path: '/egypt-through-time/military-history/map'
      fullPath: '/egypt-through-time/military-history/map'
      preLoaderRoute: typeof EgyptThroughTimeMilitaryHistoryMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egypt-through-time_/military-history_/records': {
      id: '/egypt-through-time_/military-history_/records'
      path: '/egypt-through-time/military-history/records'
      fullPath: '/egypt-through-time/military-history/records'
      preLoaderRoute: typeof EgyptThroughTimeMilitaryHistoryRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egypt-through-time_/military-history_/timeline': {
      id: '/egypt-through-time_/military-history_/timeline'
      path: '/egypt-through-time/military-history/timeline'
      fullPath: '/egypt-through-time/military-history/timeline'
      preLoaderRoute: typeof EgyptThroughTimeMilitaryHistoryTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-like-an-egyptian_/$section_/$slug': {
      id: '/live-like-an-egyptian_/$section_/$slug'
      path: '/live-like-an-egyptian/$section/$slug'
      fullPath: '/live-like-an-egyptian/$section/$slug'
      preLoaderRoute: typeof LiveLikeAnEgyptianSectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$type/$id': {
      id: '/partners/$type/$id'
      path: '/partners/$type/$id'
      fullPath: '/partners/$type/$id'
      preLoaderRoute: typeof PartnersTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/$provider': {
      id: '/api/public/hooks/$provider'
      path: '/api/public/hooks/$provider'
      fullPath: '/api/public/hooks/$provider'
      preLoaderRoute: typeof ApiPublicHooksProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egypt-through-time_/military-history_/figures_/$slug': {
      id: '/egypt-through-time_/military-history_/figures_/$slug'
      path: '/egypt-through-time/military-history/figures/$slug'
      fullPath: '/egypt-through-time/military-history/figures/$slug'
      preLoaderRoute: typeof EgyptThroughTimeMilitaryHistoryFiguresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egypt-through-time_/military-history_/records_/$slug': {
      id: '/egypt-through-time_/military-history_/records_/$slug'
      path: '/egypt-through-time/military-history/records/$slug'
      fullPath: '/egypt-through-time/military-history/records/$slug'
      preLoaderRoute: typeof EgyptThroughTimeMilitaryHistoryRecordsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContentTableRoute: typeof AdminContentTableRoute
  AdminCrmInvestmentRoute: typeof AdminCrmInvestmentRoute
  AdminCrmPropertiesRoute: typeof AdminCrmPropertiesRoute
  AdminPartnersNewRoute: typeof AdminPartnersNewRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContentTableRoute: AdminContentTableRoute,
  AdminCrmInvestmentRoute: AdminCrmInvestmentRoute,
  AdminCrmPropertiesRoute: AdminCrmPropertiesRoute,
  AdminPartnersNewRoute: AdminPartnersNewRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeAPartnerRoute: BecomeAPartnerRoute,
  ContactRoute: ContactRoute,
  CountriesRoute: CountriesRoute,
  DoBusinessRoute: DoBusinessRoute,
  EgyptAppsRoute: EgyptAppsRoute,
  EgyptThroughTimeRoute: EgyptThroughTimeRoute,
  EgyptianHeritageWorldwideRoute: EgyptianHeritageWorldwideRoute,
  EmergencyNumbersRoute: EmergencyNumbersRoute,
  EncyclopediaRoute: EncyclopediaRoute,
  EventsRoute: EventsRoute,
  ExploreEgyptRoute: ExploreEgyptRoute,
  FaqRoute: FaqRoute,
  GovernmentRoute: GovernmentRoute,
  GovernmentDirectoryRoute: GovernmentDirectoryRoute,
  HeritageSitesRoute: HeritageSitesRoute,
  InvestInEgyptRoute: InvestInEgyptRoute,
  InvestmentOpportunitiesRoute: InvestmentOpportunitiesRoute,
  KnowYourRootsRoute: KnowYourRootsRoute,
  LiveInEgyptRoute: LiveInEgyptRoute,
  LiveLikeAnEgyptianRoute: LiveLikeAnEgyptianRoute,
  MuseumsRoute: MuseumsRoute,
  OffersRoute: OffersRoute,
  OurMissionRoute: OurMissionRoute,
  PhotoCreditsRoute: PhotoCreditsRoute,
  ProductsRoute: ProductsRoute,
  PropertiesRoute: PropertiesRoute,
  ProvidersRoute: ProvidersRoute,
  RealEstateRoute: RealEstateRoute,
  ResearchProgramsRoute: ResearchProgramsRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  TravelerStoriesRoute: TravelerStoriesRoute,
  TrustCenterRoute: TrustCenterRoute,
  VisionValuesRoute: VisionValuesRoute,
  VisitEgyptRoute: VisitEgyptRoute,
  AccountBookingsRoute: AccountBookingsRoute,
  ApiConciergeRoute: ApiConciergeRoute,
  CountriesIdRoute: CountriesIdRoute,
  DoBusinessGuideRoute: DoBusinessGuideRoute,
  EgyptAppsCategoryRoute: EgyptAppsCategoryRoute,
  EgyptThroughTimeMilitaryHistoryRoute: EgyptThroughTimeMilitaryHistoryRoute,
  EgyptianHeritageWorldwideIdRoute: EgyptianHeritageWorldwideIdRoute,
  EventsIdRoute: EventsIdRoute,
  ExperiencesTypeRoute: ExperiencesTypeRoute,
  GovernmentDirectoryDigitalServicesRoute:
    GovernmentDirectoryDigitalServicesRoute,
  GovernoratesIdRoute: GovernoratesIdRoute,
  HeritageSitesIdRoute: HeritageSitesIdRoute,
  InvestmentOpportunitiesIdRoute: InvestmentOpportunitiesIdRoute,
  LegalSlugRoute: LegalSlugRoute,
  LegalConsentRoute: LegalConsentRoute,
  LegalReviewChecklistRoute: LegalReviewChecklistRoute,
  LiveInEgyptGuideRoute: LiveInEgyptGuideRoute,
  LiveLikeAnEgyptianSectionRoute: LiveLikeAnEgyptianSectionRoute,
  MarketplaceEgyptianCottonRoute: MarketplaceEgyptianCottonRoute,
  MarketplaceHandmadeCraftsRoute: MarketplaceHandmadeCraftsRoute,
  MarketplaceLocalProducersRoute: MarketplaceLocalProducersRoute,
  MarketplaceWearEgyptRoute: MarketplaceWearEgyptRoute,
  MuseumsIdRoute: MuseumsIdRoute,
  MyTripsNewRoute: MyTripsNewRoute,
  OffersIdRoute: OffersIdRoute,
  PlacesIdRoute: PlacesIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  ProvidersIdRoute: ProvidersIdRoute,
  ResearchProgramsIdRoute: ResearchProgramsIdRoute,
  TravelerStoriesIdRoute: TravelerStoriesIdRoute,
  TripsIdRoute: TripsIdRoute,
  VisitEgyptEVisaRoute: VisitEgyptEVisaRoute,
  VisitEgyptTravelAndTourismRoute: VisitEgyptTravelAndTourismRoute,
  GovernoratesIndexRoute: GovernoratesIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MyTripsIndexRoute: MyTripsIndexRoute,
  PartnersIndexRoute: PartnersIndexRoute,
  EgyptThroughTimeMilitaryHistoryFiguresRoute:
    EgyptThroughTimeMilitaryHistoryFiguresRoute,
  EgyptThroughTimeMilitaryHistoryLibraryRoute:
    EgyptThroughTimeMilitaryHistoryLibraryRoute,
  EgyptThroughTimeMilitaryHistoryMapRoute:
    EgyptThroughTimeMilitaryHistoryMapRoute,
  EgyptThroughTimeMilitaryHistoryRecordsRoute:
    EgyptThroughTimeMilitaryHistoryRecordsRoute,
  EgyptThroughTimeMilitaryHistoryTimelineRoute:
    EgyptThroughTimeMilitaryHistoryTimelineRoute,
  LiveLikeAnEgyptianSectionSlugRoute: LiveLikeAnEgyptianSectionSlugRoute,
  PartnersTypeIdRoute: PartnersTypeIdRoute,
  ApiPublicHooksProviderRoute: ApiPublicHooksProviderRoute,
  EgyptThroughTimeMilitaryHistoryFiguresSlugRoute:
    EgyptThroughTimeMilitaryHistoryFiguresSlugRoute,
  EgyptThroughTimeMilitaryHistoryRecordsSlugRoute:
    EgyptThroughTimeMilitaryHistoryRecordsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
